### ISSUE TITLE
Add in bower support?

### ISSUE THREAD

**Issue by michaelryancaputo** [stherrienaspnet/ngRadialGauge#1]
Any chance you can add bower support?

**Comment by stherrienaspnet** [comment]
I'm sorry I don't know anything about bower  implementation. But if you
would like to add it I could add you to my repository.
Stéphane :)

**Comment by noducks** [comment]
+1 for bower support.

http://bower.io/docs/creating-packages/

**Comment by stherrienaspnet** [comment]
I will try to add it tonight

**Comment by frankthelen** [comment]
+1 very cool. thanks.

**Comment by stherrienaspnet** [comment]
I think now bower should work!
