### ISSUE TITLE
Setting Gauge width

### ISSUE THREAD

**Issue by colinbes** [stherrienaspnet/ngRadialGauge#12]
How would one set a % width for a gauge?

Specifying width="80%" results in width being set to 80 and not 80% of the available width.

Thanks

**Comment by colinbes** [comment]
Using viewBox to set viewbox size (viewBox='0 0 300 225) and then using width as 100% makes gauge nice and responsive.

**Comment by stherrienaspnet** [comment]
Nice!

On Thu, Aug 13, 2015 at 5:25 PM, Colin Bester notifications@github.com
wrote:

> Using viewBox to set viewbox size (viewBox='0 0 300 225) and then using
> width as 100% makes gauge nice and responsive.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stherrienaspnet/ngRadialGauge/issues/12#issuecomment-130848997
> .

##

**Comment by stherrienaspnet** [comment]
The way manage to make it work usually with my component is to use scope
variable to adjust size. So in the function setDimension you can apply any
transformation.

$($window).resize(function () {
        setDimension();
        $scope.$apply();
    });

```
function setDimension() {
    var marginWidth = 18;
    var marginGrid = 12;
    $scope.dimension.gauge= $window.innerWidth - marginWidth;
    $scope.dimension.gridWidth = $window.innerWidth - marginWidth -
```

marginGrid;
        $scope.dimension.gridHeight = $window.innerHeight - marginTop;
    };

Hope this will help you. There may be a better way to acheive this :)

On Thu, Aug 13, 2015 at 4:06 PM, Colin Bester notifications@github.com
wrote:

> How would one set a % width for a gauge?
> 
> Specifying width="80%" results in width being set to 80 and not 80% of the
> available width.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stherrienaspnet/ngRadialGauge/issues/12.

##
