### ISSUE TITLE
Changing font family of gauges

### ISSUE THREAD

**Issue by NicTorgersen** [stherrienaspnet/ngRadialGauge#15]
Is it possible to change the font family of the gauges? I can't seem to do it.

**Comment by stherrienaspnet** [comment]
Hello, i did not take care of this situation in my coding. I will look soon
to add a parameter for this option and let you know.

Best regards,

Stephane

On Mon, Sep 28, 2015 at 5:49 AM, Nichlas Torgersen <notifications@github.com

> wrote:
> 
> Is it possible to change the font family of the gauges? I can't seem to do
> it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stherrienaspnet/ngRadialGauge/issues/15.

##

**Comment by leonardojc** [comment]
Hi, how can i change the size of fonts ?
thanks!

**Comment by stherrienaspnet** [comment]
Changing the size of the font require code adjustment because of the
position of the label.
