### ISSUE TITLE
Chaging the ViewBox height

### ISSUE THREAD

**Issue by EduardoOliveira** [stherrienaspnet/ngRadialGauge#19]
Hi
I am using the radial gauge with an angle='90' and with needle-value-text-size='0' generating a SVG object with more height than what is really needed.

Is there a way to change that without changing the directive itself?

**Comment by EduardoOliveira** [comment]
Is the issue solved?

**Comment by stherrienaspnet** [comment]
Sorry my response time so long, i though you already find a way to acheive what you are trying to do. I have difficulty to see what is the issue clearly. If you could send me a rapidly a plunker, i should be able to look at it today and maybe bring some changes if required :)
