### ISSUE TITLE
is it possible to give hover on gauge chart

### ISSUE THREAD

**Issue by pgksunilkumar** [stherrienaspnet/ngRadialGauge#22]
I am trying to giving hover it's not working 

http://plnkr.co/edit/S91OOjg5h3dIoFFO68ZC

**Comment by stherrienaspnet** [comment]
Let me know if the following plunker is working for you case...
[http://plnkr.co/edit/uiJHKCHQ1XgvgsEOyJCZ?p=preview](url)

**Comment by pgksunilkumar** [comment]
hello stherrienaspnet,

the link is not working please check and update me

**Comment by stherrienaspnet** [comment]
Try this one

http://plnkr.co/edit/uiJHKCHQ1XgvgsEOyJCZ?p=preview

**Comment by pgksunilkumar** [comment]
![untitled](https://user-images.githubusercontent.com/11393456/27896379-433fb180-6237-11e7-9e02-6f1d7a4f4932.png)

I need this type of hover if you hover the graph it will show like this is it possible...?

**Comment by stherrienaspnet** [comment]
Sorry for the delay. This will require changes in the directive and since I'm really busy at work i will not be able to adapt it.
