### ISSUE TITLE
Trying to bind gauge but wont work

### ISSUE THREAD

**Issue by matthewd92** [stherrienaspnet/ngRadialGauge#3]
We are attempting to use the gauge with Firebase and need to bind it to update as the data source updates.  We have tried putting $scope.value in the $loaded() function but it does not work.  Do you have any ideas on how we can bind the value to an object in the function?

**Comment by stherrienaspnet** [comment]
Hello Matt, could you provide me a sample so I can fix it?

**Comment by matthewd92** [comment]
We were able to get it working last night, just had to move where we were
calling the $scope.value outside of the $loaded() and into the function
that is being called from the $loaded().

Thanks,
Matt

_Matthew Bush_
Director of Operations
Scott Fetzer Electrical Group
Direct: 615-799-1123
Mobile: 615-598-4387

On Mon, Mar 16, 2015 at 6:26 PM, stherrienaspnet notifications@github.com
wrote:

> Hello Matt, could you provide me a sample so I can fix it?
> On Mar 16, 2015 7:18 PM, "Matt" notifications@github.com wrote:
> 
> > We are attempting to use the gauge with Firebase and need to bind it to
> > update as the data source updates. We have tried putting $scope.value in
> > the $loaded() function but it does not work. Do you have any ideas on how
> > we can bind the value to an object in the function?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/stherrienaspnet/ngRadialGauge/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stherrienaspnet/ngRadialGauge/issues/3#issuecomment-81988639
> .

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by stherrienaspnet** [comment]
Glad it worked Matt!

If you can only , i will be happy to see a capture of your gauge usage.

Steph :)

On Tue, Mar 17, 2015 at 8:59 AM, Matt notifications@github.com wrote:

> We were able to get it working last night, just had to move where we were
> calling the $scope.value outside of the $loaded() and into the function
> that is being called from the $loaded().
> 
> Thanks,
> Matt
> 
> _Matthew Bush_
> Director of Operations
> Scott Fetzer Electrical Group
> Direct: 615-799-1123
> Mobile: 615-598-4387
> 
> On Mon, Mar 16, 2015 at 6:26 PM, stherrienaspnet <notifications@github.com
> 
> > wrote:
> > 
> > Hello Matt, could you provide me a sample so I can fix it?
> > On Mar 16, 2015 7:18 PM, "Matt" notifications@github.com wrote:
> > 
> > > We are attempting to use the gauge with Firebase and need to bind it to
> > > update as the data source updates. We have tried putting $scope.value
> > > in
> > > the $loaded() function but it does not work. Do you have any ideas on
> > > how
> > > we can bind the value to an object in the function?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/stherrienaspnet/ngRadialGauge/issues/3.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/stherrienaspnet/ngRadialGauge/issues/3#issuecomment-81988639
> > 
> > .
> 
> ## 
> 
> This email and any files transmitted with it are confidential and intended
> solely for the use of the individual or entity to whom they are addressed.
> If you have received this email in error please notify the system manager.
> This message contains confidential information and is intended only for
> the
> individual named. If you are not the named addressee you should not
> disseminate, distribute or copy this e-mail. Please notify the sender
> immediately by e-mail if you have received this e-mail by mistake and
> delete this e-mail from your system. If you are not the intended recipient
> you are notified that disclosing, copying, distributing or taking any
> action in reliance on the contents of this information is strictly
> prohibited.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stherrienaspnet/ngRadialGauge/issues/3#issuecomment-82332147
> .

##
