### ISSUE TITLE
Bower support not working

### ISSUE THREAD

**Issue by frankthelen** [stherrienaspnet/ngRadialGauge#5]
Thanks very much for adding Bower support. But it doesn't seam to work. A few comments (I'm not a bower expert though)...
1. "bower info ngRadialGauge" responds with "ENOTFOUND Package ngRadialGauge not found". Did you register your package at the Bower registry?
2. The file "bower.json" is usually located at the root level of a GIT repo. But I'm not sure if this is a requirement. Might be depending on how you register your package.
3. "main" in "bower.json" are the files to be installed by bower to use your package. "index.html" cannot be correct here. Should rather be js and css files; and in case you need any templates html as well.
4. The "version" in your "bower.json" says "1.0.0". But there is not version "1.0.0" in your repo.
5. The "dependencies" in your "bower.json" are too restrictive I believe; e.g., "angular":"~1.2.28" is not matching Angular 1.3.x. But it should (I am using ngRadialGauge successfully with AngularJS 1.3.15). "angular":"'~1" should be ok I think. Same with d3.
6. I'm not sure if it works when you define your directive like this: "app.directive('ngRadialGauge',...)" because "app" is not necessarily defined (unless you do that yourself). You need to define your own Angular module. Something like this: "angular.module('ngRadialGauge').directive(...);"

Just my two cents.
Hope it helps.

**Comment by stherrienaspnet** [comment]
Thanks you very much for your feedback, I will follow your information's.
Could I add you to my repository?

**Comment by frankthelen** [comment]
Sure. :-)

**Comment by stherrienaspnet** [comment]
Could you make the appropriate change to make it work?

**Comment by frankthelen** [comment]
Theoretically yes. Have done a lot with Angular but not yet provided a module for third-party usage. Anyway, I could try.
Best regards,
Frank

**Comment by stherrienaspnet** [comment]
Hello Frank,
I just added you as repository member, let me know if you lacking access.
The folders structure is really bad, too many levels.

Thanks you very much Frank!

**Comment by frankthelen** [comment]
Great. I'll take a look.

**Comment by frankthelen** [comment]
I would propose the following changes:

**(1) Project Structure (according to current best practice)**

```
/dist
/src
/test
/demo
```

Your code files will be under /src without further directories.
/dist is not really needed because in this project there is nothing to build actually.
/demo could be for your demo index.html etc.
bower.json would be in the root directory.

**(2) d3 dependency**

Your "d3Service" is definitely a good idea.

However, imagine a project that uses _multiple_ third-party components based on d3. Should they all bring their own "d3Service"? Should they use a common "d3Service"? How does that work? What about name conflicts when there are multiple services "d3Service" in different modules?

I looked at some of the other d3-based Angular components. Most of them just rely on a global "d3" object. No extra Angular service. Only the d3 dependency in bower.json.

That's what I would propse. Remove the "d3Service". Just rely on a global "d3". But have the d3 dependency in your bower.json.

**(3) Controller "RadialGaugeCtrl"**

That's only for demo purposes, right. So we wouldn't expose it via bower.

**(4) Directive "ngRadialGauge"**

There must be a separate module for your component. That's the Angular way for third-party code:

```
angular.module("ngRadialGauge").directive("ngRadialGauge", .....);
```

Remove dependency "d3Service" and just rely on global "d3".

Why do you restrict your component to attributes? Should element and class as well.

```
restrict: 'EAC',
```

What do you think? 
Does that make sense?

**Comment by stherrienaspnet** [comment]
Yes, everything make sense, thank you Frank. Have a nice day:)

**Comment by frankthelen** [comment]
I did the changes locally. Do you want me to commit? I guess you need to add me as contributor first.

**Comment by stherrienaspnet** [comment]
Yes Frank you can commit! I added you as repository member. If this not
giving you the full access right tell me the steps required to do to give
you full access.
Stephane:)

**Comment by stherrienaspnet** [comment]
Frank do you have experience with node.js?

**Comment by frankthelen** [comment]
Thanks for merging my changes in.

I registered "ngRadialGauge" at the Bower regsitry...

```
> bower info ngRadialGauge
bower ngRadialGauge#*       not-cached git://github.com/stherrienaspnet/ngRadialGauge.git#*
bower ngRadialGauge#*          resolve git://github.com/stherrienaspnet/ngRadialGauge.git#*
bower ngRadialGauge#*         checkout master
bower ngRadialGauge#*         resolved git://github.com/stherrienaspnet/ngRadialGauge.git#4a84d1f73e
...
No versions available.
```

Last thing for you to do is to release version "1.0.0" as referred to in the "bower.json".

I also tested using the package with a fresh Angular project generated by Yeoman. Works all fine.

I use your component in a project at work. I'll change that to use the new Bower package later this week.

That was fun,
Frank

**Comment by stherrienaspnet** [comment]
Too nice Frank!
